name: strooienhane
recipe: drupal8
config:
  webroot: web
  php: '8.1'
services:
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: 'https://strooienhane.lndo.site'
  mailhog:
    type: mailhog:v1.0.0
    portforward: true
    hogfrom:
      - appserver
